/**
 * kigu-quant Demo — Rosito Bench
 * Tiny tools. Big solutions.
 *
 * Demonstrates LUT and CORDIC sin evaluation on embedded hardware.
 * Headers generated by kigu-quant — no FPU, no libm, no dependencies.
 *
 * Compatible: ESP32, ESP8266, Arduino + Ethernet/WiFi shield
 *
 * ESP32 / ESP8266:
 *   - Set WIFI_SSID and WIFI_PASSWORD below
 *   - Open Serial Monitor at 115200 to get the IP address
 *   - Open browser: http://<ip>/
 *
 * Board: ESP32-C3 Super Mini (tested)
 */

#include <Arduino.h>

// ── WiFi ──────────────────────────────────────────────────────────────────────
#if defined(ESP32) || defined(ARDUINO_ARCH_ESP32)
  #include <WiFi.h>
  #include <WebServer.h>
  WebServer server(80);
#elif defined(ESP8266) || defined(ARDUINO_ARCH_ESP8266)
  #include <ESP8266WiFi.h>
  #include <ESP8266WebServer.h>
  ESP8266WebServer server(80);
#else
  #error "Unsupported board: this sketch requires ESP32 or ESP8266"
#endif

const char* WIFI_SSID     = "your-ssid";
const char* WIFI_PASSWORD = "your-password";

// ── kigu-quant generated headers ─────────────────────────────────────────────
#include "lut_sin.h"      // LUT backend,   256 points, Q1.15
#include "cordic_sin.h"   // CORDIC backend, 16 iters,  Q1.15

// ── Evaluate both at N points and return as JSON ─────────────────────────────
#define DEMO_POINTS 128

String build_json() {
  String json = "{\"labels\":[";

  // X axis: 0..2pi over DEMO_POINTS
  for (int i = 1; i < DEMO_POINTS; i++) {
    float x = (float)i / (DEMO_POINTS ) * 6.2831853f;
    json += String(x, 4);
    if (i < DEMO_POINTS - 1) json += ",";
  }
  json += "],\"lut\":[";

  for (int i = 1; i < DEMO_POINTS; i++) {
    float x = (float)i / (DEMO_POINTS ) * 6.2831853f;
    float v = lut_sin_lookup(x);
    json += String(v, 5);
    if (i < DEMO_POINTS - 1) json += ",";
  }
  json += "],\"cordic\":[";

  for (int i = 1; i < DEMO_POINTS; i++) {
    float x = (float)i / (DEMO_POINTS ) * 6.2831853f;
    float v  = cordic_sin_lookup(x);
    json += String(v, 5);
    if (i < DEMO_POINTS - 1) json += ",";
  }
  json += "]}";
  return json;
}

// ── HTML page ────────────────────────────────────────────────────────────────
static const char HTML[] PROGMEM = R"html(
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>kigu-quant Demo</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: 'Segoe UI', system-ui, sans-serif;
    background: #0d1117;
    color: #e6edf3;
    padding: 2rem;
  }
  h1 {
    font-size: 1.4rem;
    font-weight: 600;
    margin-bottom: 0.25rem;
    color: #58a6ff;
    letter-spacing: 0.05em;
  }
  .sub {
    font-size: 0.85rem;
    color: #8b949e;
    margin-bottom: 2rem;
  }
  .grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 1.5rem;
    max-width: 960px;
  }
  @media (max-width: 640px) { .grid { grid-template-columns: 1fr; } }
  .card {
    background: #161b22;
    border: 1px solid #30363d;
    border-radius: 8px;
    padding: 1.25rem;
  }
  .card h2 {
    font-size: 0.9rem;
    font-weight: 600;
    margin-bottom: 0.25rem;
    color: #e6edf3;
  }
  .card p {
    font-size: 0.75rem;
    color: #8b949e;
    margin-bottom: 1rem;
  }
  canvas { width: 100% !important; }
  .footer {
    margin-top: 2rem;
    font-size: 0.75rem;
    color: #484f58;
  }
  .footer a { color: #58a6ff; text-decoration: none; }
</style>
</head>
<body>
<h1>kigu-quant 器具</h1>
<p class="sub">Small tools. Precise work. — Headers generated by kigu-quant, evaluated on this device.</p>

<div class="grid">
  <div class="card">
    <h2>LUT — sin(x)</h2>
    <p>256-point lookup table · Q1.15 · linear interpolation</p>
    <canvas id="chartLut"></canvas>
  </div>
  <div class="card">
    <h2>CORDIC — sin(x)</h2>
    <p>16 iterations · Q1.15 · error &lt; 1e-4</p>
    <canvas id="chartCordic"></canvas>
  </div>
</div>

<div class="footer">
  Running on <strong id="chip">ESP32</strong> &nbsp;|&nbsp;
  <a href="https://github.com/AlexRosito67" target="_blank">Rosito Bench</a>
</div>

<script>
async function init() {
  const res  = await fetch('/data');
  const data = await res.json();

  const cfg = (label, values, color) => ({
    type: 'line',
    data: {
      labels: data.labels.map(x => x.toFixed(2)),
      datasets: [{
        label,
        data: values,
        borderColor: color,
        borderWidth: 1.5,
        pointRadius: 0,
        tension: 0.3
      }]
    },
    options: {
      animation: false,
      plugins: { legend: { display: false } },
      scales: {
        x: {
          ticks: { color: '#8b949e', maxTicksLimit: 6, font: { size: 10 } },
          grid:  { color: '#21262d' }
        },
        y: {
          min: -1.1, max: 1.1,
          ticks: { color: '#8b949e', font: { size: 10 } },
          grid:  { color: '#21262d' }
        }
      }
    }
  });

  new Chart(document.getElementById('chartLut'),    cfg('LUT',    data.lut,    '#58a6ff'));
  new Chart(document.getElementById('chartCordic'), cfg('CORDIC', data.cordic, '#3fb950'));
}
init();
</script>
</body>
</html>
)html";

// ── Route handlers ────────────────────────────────────────────────────────────
void handle_root() {
  server.send_P(200, "text/html", HTML);
}

void handle_data() {
  String json = build_json();
  server.send(200, "application/json", json);
}

void handle_not_found() {
  server.send(404, "text/plain", "Not found");
}

// ── Benchmark ────────────────────────────────────────────────────────────────
void benchmark() {
  const int N = 1000;
  float dummy = 0;  

  // std::sin
  uint32_t t0 = micros();
  for (int i = 0; i < N; i++) {
    float x = (float)i / N * 6.2831853f;
    dummy += sinf(x);
  }
  uint32_t t1 = micros();

  // CORDIC lookup
  uint32_t t2 = micros();
  for (int i = 0; i < N; i++) {
    float x = (float)i / N * 6.2831853f;
    dummy += cordic_sin_lookup(x);
  }
  uint32_t t3 = micros();

  Serial.print("sinf: ");
  Serial.println(t1 - t0);
  Serial.print("cordic: ");
  Serial.println(t3 - t2);
  Serial.print("dummy (anti-optimize): ");
  Serial.println(dummy);
  Serial.print("ratio: ");
  Serial.println((float)(t1-t0)/(float)(t3-t2));
}


// ── Setup / Loop ──────────────────────────────────────────────────────────────
void setup() {
  Serial.begin(115200);
  delay(500);

  Serial.println("\nkigu-quant Demo — Rosito Bench");
  Serial.println("Connecting to WiFi...");

  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  Serial.println();
  Serial.print("Connected. IP: ");
  Serial.println(WiFi.localIP());
  Serial.println("Open your browser and navigate to http://" + WiFi.localIP().toString());

  server.on("/",     handle_root);
  server.on("/data", handle_data);
  server.onNotFound(handle_not_found);
  server.begin();

  Serial.println("WebServer started on port 80.");

  benchmark();
}

void loop() {
  server.handleClient();
}
